// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqpqsdoxibxgqoappbcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxcHFzZG94aWJ4Z3FvYXBwYmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDk2NTMsImV4cCI6MjA2Njc4NTY1M30.bEvuGp-g4r4khUdc9QtqTw8fWabnE3sD4YdCYu-v7Jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);